name: Build

on:
  push:
    branches:
      - 'main' 
    
  pull_request:
    branches:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Convert the YAML to GeoJSON
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run build

      - name: Build Icons
        run: |
          cd $GITHUB_WORKSPACE
          node .github/workflows/icon-build.js $GITHUB_WORKSPACE

      - name: Set index.html for preview
        run: |
          cd $GITHUB_WORKSPACE
          mv .github/workflows/index.html ./index.html

      - name: Deploy
        uses: shlinkio/deploy-preview-action@v1.0.1
        with:
          branch: gh-pages
          folder: '.'