name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Convert the YAML to GeoJSON
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run build
          npm run build:icon
          echo "charites" > .gitignore

      - name: Build Icons
        run: |
          cd $GITHUB_WORKSPACE
          
      - name: Set index.html for preview
        run: |
          cd $GITHUB_WORKSPACE
          mv .github/workflows/index.html ./index.html

      - name: Deploy the GeoJSON to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true