name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Replace sprite url
        run: |
          cd $GITHUB_WORKSPACE
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          node .github/workflows/replace-url.js
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Replace sprite url by GitHub Actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi

      - name: Install the `charites`
        run: |
          npm install -g @unvt/charites
          
      - name: Convert the YAML to GeoJSON
        run: |
          cd $GITHUB_WORKSPACE
          charites build style.yml style.json
          echo "charites" > .gitignore

      - name: Build Icons
        run: |
          cd $GITHUB_WORKSPACE
          npm install -g @mapbox/spritezero glob
          node .github/workflows/icon-build.js $GITHUB_WORKSPACE

      - name: Set index.html for preview
        run: |
          cd $GITHUB_WORKSPACE
          mv .github/workflows/index.html ./index.html

      - name: Deploy the GeoJSON to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true