name: Deploy

on:
  deployment:
  deployment_status:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Test
        run: console.log("hello")